### ISSUE TITLE
 The alternative resizing method doesn't work

### ISSUE THREAD

**Issue by EtreRe** [flyimg/flyimg#151]
The alternative resizing method doesn't seem to work.

I have tried it on a local docker environment with no success and the example online have the same issue.

You can see that with or without rz_1 the result is the same : 

https://oi.flyimg.io/upload/w_300,h_250,rz_1/https://m0.cl/t/resize-test_1920.jpg

![](https://oi.flyimg.io/upload/w_300,h_250,rz_1/https://m0.cl/t/resize-test_1920.jpg)

https://oi.flyimg.io/upload/w_300,h_250/https://m0.cl/t/resize-test_1920.jpg

![](https://oi.flyimg.io/upload/w_300,h_250/https://m0.cl/t/resize-test_1920.jpg)

**Comment by sadok-f** [comment]
Thank you for submitting the issue, I'll close it  due to the fact that -thumbnail works just like -resize does with a few differences:
- It is optimized for speed.
- It also removes any embedded color profiles to reduce the filesize of the thumbnails.

If you look to crop the image, you can use the option `c_1`

if you pass the refresh option `rf_1` you'll get the full command generated by ImageMagick in the response header.

**Comment by EtreRe** [comment]
My mistake, I thought that rz_1 would force the result to the have the size passed in the parameters, filling the rest of the image with background color.

**Comment by sadok-f** [comment]
no worries,
I curious question, do you use flyimg in some a production? or just for testing?

**Comment by EtreRe** [comment]
Testing for now but we are hoping to use it in production if we can make it fit our needs
