### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by vojtasvoboda** [flyimg/flyimg#157]
Just question - is that [image](https://hub.docker.com/r/flyimg/flyimg-build/) comes directly from this [Dockerfile](https://github.com/flyimg/flyimg/blob/master/Dockerfile)? Why there is no automatic build on Docker Hub?

Thanks a lot :-)

**Comment by sadok-f** [comment]
Hi,
There's no automatic build for https://hub.docker.com/r/flyimg/flyimg-build because it uses a Makefile to create a clean image based on the latest release of Flyimg.
Here the GitHub repo and you can check the Makefile: https://github.com/flyimg/flyimg-build
in order to release a new docker-build image, we have to run `make push` command.

On the other hand, the main docker image for Flyimg https://hub.docker.com/r/flyimg/docker-app has an automatic build option.

I hope this answer your question :)
