### ISSUE TITLE
Instructions to install on server and webp

### ISSUE THREAD

**Issue by Allmedialab** [flyimg/flyimg#259]
Hi,

I'm looking for simple instructions to install flyimg on my server and wonder if webp is supported.

Regards & Thanks,

David

**Comment by sadok-f** [comment]
Hi @Allmedialab ,

Thank you for opening the issue, 
we provide simple documentation on how you can run Flyimg using docker on any host.
If you want to have a self-installed version, you can check the Dockerfile in the main folder but be sure you have all dependencies installed in your server (that's why we provide a ready docker image).
And yes Webp is supported by default

Thank you again!

Best,
Sadok
