### ISSUE TITLE
PDF resolution option

### ISSUE THREAD

**Issue by v1o** [flyimg/flyimg#303]
Hi, is there a way to specify the PDF render resolution?
Thank you.

**Comment by sadok-f** [comment]
Hi @v1o ,
Thank you for your issue, unfortunately, such an option doesn't exist

**Comment by v1o** [comment]
Would you be able to point me in the right direction? We could build a custom image with some modified ghostscript params.

**Comment by v1o** [comment]
I saw ghostscript being installed in this image and not the base one, but I couldn't find any reference to it in the code.

**Comment by sadok-f** [comment]
The thing is this feature was added by another contributor, I thought also it is using `ghostscript ` but it seems no isn't used.

If you add `rf_1` to refresh the image, in the response headers there's one called ` im-command` which shows the full command used to generate the final image.

For the PDF case, it uses imagemagick (it could be imagemagick needs ghostscript to read from the PDF but I'm not sure and I need to debug more).

Since it is a imagemagick cmd, you can increase the quality (default 90) to 100 by adding `q_100` option, also you can try to generate a different format such PNG with `o_png` option.

**Comment by louisl** [comment]
Was just looking around and saw this. It's been a while since I made that feature. Ghostscript was/is? indeed a requirement for imagemagick to handle PDF's and not used directly as mentioned.

**Comment by sadok-f** [comment]
Thank you @louisl for clarifying this, maybe we should add it to README file.

**Comment by v1o** [comment]
Thank you @sadok-f, the `rf_1` flag really helped.

I was unable to use `quality` option for my purpose since ImageMagick uses it in the post-process part of the convert operation.

In the end I've used the [`-density`](https://imagemagick.org/script/command-line-options.php#density) option which does the trick when used correctly (before the input file).

I've pushed the changes [here](https://github.com/flyimg/flyimg/compare/main...v1o:pdf-density?expand=1) and updated the documentation as well. If it matches your coding standards I can send over a pull-request.

Again, thank you for your help.

**Comment by sadok-f** [comment]
Thank you @v1o !
Glad to hear you're able to fix that, would be great if you can send the pull request.

**Comment by v1o** [comment]
Just sent the pull request.

**Comment by v1o** [comment]
Just sent the pull request.
