### ISSUE TITLE
Documentation for image upload

### ISSUE THREAD

**Issue by peraronsson** [flyimg/flyimg#450]
Hello, and thanks for a great application!
We have deployed Flyimg on AWS with S3 storage. How do we ingest images to the storage? Are there any naming conventions to follow in order to be able to request the images from the web server? Can we organise images into "folders" and "sub-folders" in the storage? Is there an api for importing images? I have browsed the documentation, but didn't find anything on this topic.

**Comment by sadok-f** [comment]
Hi @peraronsson 
thank you for opening this issue.
I'll try to answer your questions:
- `How do we ingest images to the storage?`: the images are fetched when the source passed to the second URL parameter, such as `/upload/q_90/https://picsum.photos/200/300` when this image get generated the first time

**Comment by sadok-f** [comment]
Hi @peraronsson 
thank you for opening this issue.
I'll try to answer your questions:
- `How do we ingest images to the storage?`: the images are fetched when the source passed to the second URL parameter, such as `/upload/q_90/https://picsum.photos/200/300` when this image gets generated the first time Flyimg will store the source image and the generated image in the System Storage configured, which in your case S3
- `Are there any naming conventions to follow in order to be able to request the images from the web server` No, but if the source image contains some parameters, then it is better to URL encode the whole URL source.
- `Can we organise images into "folders" and "sub-folders" in the storage` No, the images are stored in the main folder.

The caching system hashes each image along with its parameters in the upload folder to be able to fetch it later on.

I hope that answers your questions, please feel free to add more details about your setup.

**Comment by peraronsson** [comment]
When using the upload call, like `/upload/q_90/https://picsum.photos/200/300`, will the image be stored permanently, or is this actually the cache that you are populating?

**Comment by sadok-f** [comment]
the source image will be stored permanently, so the next call will fetch from the local folder, to fetch again the image from the source the refresh option should be used `rf_1`

**Comment by peraronsson** [comment]
It seems a bit risky to have this upload feature without any api key or similar. A malicious person could potentially upload huge amounts of images and exhaust the storage... Is there any way to prevent that?

**Comment by sadok-f** [comment]
well there is `restricted_domains` option where it allows images only from a defined list of domains: https://github.com/flyimg/flyimg/blob/main/docs/full-documentation.md#security-restricting-source-domains

Another option is to use Signature Generation:
https://github.com/flyimg/flyimg/blob/main/docs/full-documentation.md#security-signature-generation

**Comment by sadok-f** [comment]
Hi @peraronsson 
did the comments here answer your questions? if yes can we close the issue then?

**Comment by peraronsson** [comment]
Yes, thank you!
