### ISSUE TITLE
Cache retention & purge

### ISSUE THREAD

**Issue by w3blogfr** [flyimg/flyimg#484]
Hello,

I would like to know how local file cache is cleaned. 

I see we can configure header_cache_days for browser, but are you also using this value to delete file after x days?

In some other questions, I saw you advice some people to clean the folder manually so I have some doubt about the cache cleaning mechanism?

Could you clarify how it's working?

Thanks in advance.

**Comment by sadok-f** [comment]
Thank you @w3blogfr for opening this issue.
I'm currently on vacation until the end of August.
As soon as I get back I will check it out.

**Comment by sadok-f** [comment]
Hi @w3blogfr,
sorry for taking so long to answer your question, currently, there is no mechanism that deletes the cache from the server side after x days, the `header_cache_days` is only used on the browser side.
I'm still thinking of cronjob or a service to be configured inside the container that does that.
I'll let you know once it gets implemented.

**Comment by tecnologiascds** [comment]
> Hi @w3blogfr, sorry for taking so long to answer your question, currently, there is no mechanism that deletes the cache from the server side after x days, the `header_cache_days` is only used on the browser side. I'm still thinking of cronjob or a service to be configured inside the container that does that. I'll let you know once it gets implemented.

Hello @sadok-f Thanks for all the work. 

Taking advantage of this issue, I would also like to propose an auto-purge for the images stored in the tmp  /var/www/html/var/tmp/ folder. 

We use imgfly to serve a large number of images, and every 4 to 5 hours, I have to manually delete the contents of the tmp folder because we run out of disk space. 

`Message: Warning: file_put_contents(/var/www/html/var/tmp/original-d576f4c96a28336b947f23db080c63bd): Failed to open stream: No space left on device`

It would be very useful if the images could be automatically deleted either after they are generated or at regular intervals.

Thanks so much

**Comment by sadok-f** [comment]
@tecnologiascds @w3blogfr in the latest version [1.4.6](https://github.com/flyimg/flyimg/releases/tag/1.4.6) I've added a cronjob that purges the folder var/tmp
it can be configured in the `config/parameters.yml` file by `cronjob_cleanup_interval` and `enable_cronjob_cleanup` (enabled by default)
@tecnologiascds  could you please give it a try?

**Comment by sadok-f** [comment]
Hi @tecnologiascds 
yes, there's an issue building the image with the right version, it keeps showing an older version despite the current version being updated, I'm planning to look into it.
when you update the `cronjob_cleanup_interval`, you must wait until the cronjob's next run, which defaults to 5 hours.
otherwise you can lunch it from the container manually:
```sh
docker exec flyimg ./cleanup-tmp.sh
```

**Comment by tecnologiascds** [comment]
> Hi @tecnologiascds yes, there's an issue building the image with the right version, it keeps showing an older version despite the current version being updated, I'm planning to look into it. when you update the `cronjob_cleanup_interval`, you must wait until the cronjob's next run, which defaults to 5 hours (in order to read the new interval value and update the crontab settings). otherwise you can launch it from the container manually:
> 
> ```shell
> docker exec flyimg ./cleanup-tmp.sh
> ```

Hi @sadok-f 
It works perfectly I changed the `cronjob_cleanup_interval,` and after the first execution, it is now cleaning every 15 minutes.

Would you also recommend a similar cron job to purge the cache, or are you working on a different system?

**Comment by sadok-f** [comment]
@tecnologiascds great to hear that.
regarding the cache, for now there are no plans to introduce a cronjob to purge it, as many users need the cached version to serve the images fast.
if you need to generate the images each time and there is no need for the cache, then you can disable it by setting `disable_cache: true` in the `config/parameters.yml` file.
